import type { Metadata } from "next";
import { ThemeProvider } from "./utils/ThemeContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { VendorProvider } from "./context/VendorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ClientLayout from "../components/ClientLayout";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <VendorProvider>
            <Navbar />
            <Sidebar>
              <ClientLayout>
                {children}
              </ClientLayout>
            </Sidebar>
          </VendorProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
